import { test } from 'node:test';
import assert from 'node:assert/strict';
import type { QueryResult } from '../src/core/types';
import type { DbSession } from '../src/drivers/driver';
import { generateDdl } from '../src/sql/ddl';

/**
 * A PostgreSQL server of the given release: it rejects the catalog columns and
 * views that release does not have, the way the real server does
 * ("column a.attgenerated does not exist").
 */
class FakePostgres implements DbSession {
  readonly dialect = 'postgres' as const;
  readonly asked: string[] = [];
  constructor(private readonly major: number) {}

  get serverVersion(): string {
    return `PostgreSQL ${this.major}.3`;
  }

  async query(): Promise<QueryResult> {
    throw new Error('not used');
  }

  async queryRaw(sql: string): Promise<{ columns: string[]; rows: unknown[][] }> {
    this.asked.push(sql);
    const missing = [
      { since: 12, name: 'attgenerated' },
      { since: 11, name: 'prokind' },
      { since: 10, name: 'attidentity' },
      { since: 10, name: 'pg_sequences' },
    ].find((item) => this.major < item.since && sql.includes(item.name));
    if (missing) throw new Error(`column ${missing.name} does not exist`);

    if (sql.includes('FROM pg_attribute a')) {
      return rows([
        ['id', 'integer', true, null, this.major >= 10 ? 'd' : '', '', null],
        ['label', 'text', false, "'x'::text", '', '', null],
      ]);
    }
    if (sql.includes('FROM pg_constraint')) return rows([['orders_pkey', 'p', 'PRIMARY KEY (id)']]);
    if (sql.includes('FROM pg_indexes')) return rows([]);
    if (sql.includes("obj_description(c.oid, 'pg_class')")) return rows([[null]]);
    if (sql.includes('pg_get_functiondef')) return rows([['CREATE FUNCTION public.f() RETURNS integer AS $$ SELECT 1 $$ LANGUAGE sql']]);
    if (sql.includes('pg_sequences')) return rows([[1, 1, 1, 9223372036854775807n, 1, false, 'integer']]);
    if (/FROM "public"\."orders_id_seq"/.test(sql)) return rows([[1, 1, 1, 9223372036854775807n, 1, false, 'bigint']]);
    return rows([]);
  }

  async close(): Promise<void> {}
}

function rows(values: unknown[][]): { columns: string[]; rows: unknown[][] } {
  return { columns: [], rows: values };
}

test('table DDL works on servers without attgenerated (pre-12) and attidentity (pre-10)', async () => {
  const modern = await generateDdl(new FakePostgres(16), { kind: 'table', schema: 'public', name: 'orders' });
  assert.match(modern, /create table "public"\."orders"/);
  assert.match(modern, /generated by default as identity/);

  const pg11 = await generateDdl(new FakePostgres(11), { kind: 'table', schema: 'public', name: 'orders' });
  assert.match(pg11, /generated by default as identity/, 'PostgreSQL 11 still has attidentity');
  assert.match(pg11, /constraint "orders_pkey"/);

  const pg96 = await generateDdl(new FakePostgres(9), { kind: 'table', schema: 'public', name: 'orders' });
  assert.match(pg96, /create table "public"\."orders"/);
  assert.doesNotMatch(pg96, /identity/, 'a 9.x server has no identity columns to report');
  assert.match(pg96, /default 'x'::text/);
});

test('routine DDL works on servers without prokind (pre-11)', async () => {
  for (const major of [16, 11, 10]) {
    const ddl = await generateDdl(new FakePostgres(major), { kind: 'routine', schema: 'public', name: 'f' });
    assert.match(ddl, /CREATE FUNCTION public\.f\(\)/, `PostgreSQL ${major}`);
  }
});

test('sequence DDL falls back to the sequence relation without the pg_sequences view (pre-10)', async () => {
  const modern = await generateDdl(new FakePostgres(16), { kind: 'sequence', schema: 'public', name: 'orders_id_seq' });
  assert.match(modern, /create sequence "public"\."orders_id_seq"/);
  assert.match(modern, /as integer/);

  const pg96 = await generateDdl(new FakePostgres(9), { kind: 'sequence', schema: 'public', name: 'orders_id_seq' });
  assert.match(pg96, /create sequence "public"\."orders_id_seq"/);
  assert.match(pg96, /start with 1/);
  assert.doesNotMatch(pg96, /as bigint/, 'every pre-10 sequence is a bigint, so the type is left implicit');
});
