title: Tablecloth
description: IntelliJ-grade database tools, laid over VS Code
url: https://tablecloth.kenroy.dev
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: [apos, apos, quot, quot]
  hard_wrap: false
exclude:
  - README.md
