title: Tablecloth
description: IntelliJ-grade database tools, laid over VS Code
url: https://sultanofcardio.github.io
baseurl: /tablecloth
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: [apos, apos, quot, quot]
  hard_wrap: false
exclude:
  - README.md
